cask_args appdir: '/Applications'

tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'

# Cask
cask 'appcleaner'
cask 'emacs'
cask 'qlmarkdown'
cask 'quicklook-json'

# Fonts
cask 'font-hack'
cask 'font-fontawesome'

# Packages
brew 'aspell'
brew 'bash'
brew 'bash-completion'
brew 'chruby'
brew 'diff-so-fancy'
brew 'fping'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'gopass'
brew 'hub'
brew 'hugo'
brew 'jq'
brew 'nmap'
brew 'packer'
brew 'pandoc'
brew 'pinentry-mac'
brew 'pv'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby-install'
brew 'shellcheck'
brew 'tectonic'
brew 'terraform'
brew 'tmux'
brew 'tree'
brew 'xz'
