brew 'ansible'
brew 'bash'
brew 'bash-completion'
brew 'curl', args: ['with-libressl', 'with-nghttp2']
brew 'fping'
brew 'git', args: ['with-brewed-curl']
brew 'go'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'lnav'
brew 'nmap'
brew 'nuttcp'
brew 'packer'
brew 'pt'
brew 'pv'
brew 'python'
brew 'shellcheck'
brew 'tree'
brew 'vim'
brew 'wget', args: ['with-libressl']
brew 'xz'
